apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy-reader-rolebinding
  namespace: springboot
subjects:
- kind: ServiceAccount    # 권한을 부여할 대상이 ServiceAccount
  name: default        # ehdrms2034이라는 이름의 서비스 어카운트에 권한을 부여
  namespace: default
roleRef:
  kind: Role              # Role에 정의된 권한을 부여
  name: deploy-reader    # service-role라는 이름의 Role을 대상에 연결
  apiGroup: rbac.authorization.k8s.io
