apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: springboot
  name: deploy-reader
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["apply","get","list","delete","create","patch"]
